version: '3'
services: 
    client:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes: 
            - /app/node_modelues
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - /app/node_modelues
            - .:/app
        command: ["npm", "run", "test"]
